export enum NotificationType {
  // Course related
  COURSE_ENROLLMENT = 'COURSE_ENROLLMENT',
  COURSE_COMPLETION = 'COURSE_COMPLETION',

  // Lesson related
  NEW_LESSON = 'NEW_LESSON',
  LESSON_COMPLETION = 'LESSON_COMPLETION',

  // Quiz related
  QUIZ_RESULT = 'QUIZ_RESULT',
  QUIZ_REMINDER = 'QUIZ_REMINDER',

  // DAO related
  DAO_UPDATE = 'DAO_UPDATE',
  DAO_PROPOSAL = 'DAO_PROPOSAL',
  DAO_VOTING = 'DAO_VOTING',

  // System related
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  MAINTENANCE = 'MAINTENANCE',

  // User related
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
}

export enum UserRole {
  STUDENT = 'STUDENT',
  TUTOR = 'TUTOR',
  ADMIN = 'ADMIN',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
