import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/components/providers/query-provider";

export const metadata: Metadata = {
  title: "ByteChain Academy",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/bytechain.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
